name: Nightly builds

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: gradle

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create local.properties
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > ./local.properties

    - name: Build with Gradle
      run: ./gradlew assembleDebug -Pandroid.injected.signing.store.file=none -Pandroid.injected.signing.key.alias=none

    - name: List APK files
      run: ls ./mastodon/build/outputs/apk/debug/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: moshidon-debug.apk
        path: ./mastodon/build/outputs/apk/debug/moshidon-debug.apk
